mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about_view,name='about'),
    path('contact/',views.contact_view,name='contact'),
    path('products/',views.product_list_view,name='products'),
    path('product/<slug>/',views.product_detail_view,name='product_detail_view'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path ('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns (

    path ('', include ('mainapp.urls')),
    # path ('', include ('accounts.urls')),
    # path ('', include ('basket.urls')),
    # path ('', include ('notifications.urls')),
    # path ('', include ('messenger.urls')),
    # path ('', include ('reports.urls')),
)

if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Blackberrymaz system administration'
admin.site.site_title = 'Blackberrymaz system administration'

templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block body %}
    <!-- Slider Section Start -->
    <div class="rs-slider main-home">
        <div class="rs-carousel owl-carousel" data-loop="true" data-items="1" data-margin="0" data-autoplay="true"
             data-hoverpause="true" data-autoplay-timeout="5000" data-smart-speed="800" data-dots="false"
             data-nav="false" data-nav-speed="false" data-center-mode="false" data-mobile-device="1"
             data-mobile-device-nav="false" data-mobile-device-dots="false" data-ipad-device="1"
             data-ipad-device-nav="false" data-ipad-device-dots="false" data-ipad-device2="1"
             data-ipad-device-nav2="false" data-ipad-device-dots2="false" data-md-device="1" data-md-device-nav="true"
             data-md-device-dots="false">
            {% for obj in slider %}
                <div class="slider-content slide1" style=" background: url({{ obj.image.url }});">
                    <div class="container">
                        <div class="content-part">
                            <div class="sl-sub-title wow bounceInLeft" data-wow-delay="300ms"
                                 data-wow-duration="2000ms">
                                {{ obj.text_1 }}
                            </div>
                            <h1 class="sl-title wow fadeInRight" data-wow-delay="600ms" data-wow-duration="2000ms">
                                {{ obj.text_2 }}
                            </h1>
                            {% if obj.link %}
                                <div class="sl-btn wow fadeInUp" data-wow-delay="900ms" data-wow-duration="2000ms">
                                    <a class="readon orange-btn main-home" target="_blank" href="{{ obj.link }}">{{ obj.button_text }}</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Features Section start -->

        <!-- Features Section End -->
    </div>
    <!-- Slider Section End -->

    <!-- Categories Section Start -->
    <div id="rs-categories" class="rs-categories main-home pt-90 pb-100 md-pt-60 md-pb-80">
        <div class="container">
            <div class="sec-title3 text-center mb-45">
                <div class="sub-title"> {% trans 'Ən Yaxşı Məhsullar' %}</div>
                <h2 class="title black-color">{% trans 'Populyar Məhsullarımız' %}</h2>
            </div>
            <div class="row mb-35">
                {% for obj in popular_products %}
                    <div class="col-lg-4 col-md-6 mb-30">
                        <div class="categories-items">
                            <div class="cate-images">
                                <a href="{{ obj.get_absolute_url }}"><img src="{{ obj.image.url }}"
                                                                          alt="{{ obj.title }}"></a>
                            </div>
                            <div class="contents">
                                <div class="img-part">
                                    <img src="{{ obj.f_image.url }}" alt="{{ obj.title }}">
                                </div>
                                <div class="content-wrap">
                                    <h2 class="title"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h2>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


            </div>
            <div class="col-lg-12 text-center">
                <a class="readon orange-btn main-home" href="{% url 'mainapp:products' %}">{% trans 'Məhsullar' %} </a>
            </div>
        </div>
    </div>
    <!-- Categories Section End -->
    <!-- about us css -->
    <style>
        {% for obj in breadcrumbs %}
            .rs-cta.main-home .partition-bg-wrap:after {
                background: url({{ obj.a_image_l.url }});
                background-size: cover;
                background-repeat: no-repeat;
                background-position: center;
            }

            .rs-cta.main-home .partition-bg-wrap:before {
                background: url({{obj.a_image_r.url}});
                background-size: cover;
                background-repeat: no-repeat;
                right: 0;
            }
        {% endfor %}
    </style>
    <!-- end aboutus -->
    <!-- CTA Section Start -->
    <div class="rs-cta main-home">
        <div class="partition-bg-wrap">
            <div class="container">
                <div class="row">
                    <div class="offset-lg-6 col-lg-6 pl-70 md-pl-15">
                        {% for obj in home_about %}
                            <div class="sec-title3 mb-40">
                                <h2 class="title white-color mb-16">{{ obj.h_title }}</h2>
                                <div class="desc white-color pr-100 md-pr-0">
                                    {{ obj.h_content|safe }}
                                </div>
                            </div>
                            <div class="btn-part">
                                <a class="readon orange-btn transparent"
                                   href="{% url 'mainapp:about' %}">{% trans 'Haqqımızda' %}</a>
                            </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- CTA Section End -->
    <!-- Counter Section Start -->
    <div id="rs-counter" class="rs-counter style2-about pt-100 md-pt-70">
        <div class="container">
            <div class="row couter-area">
                {% for obj in statistics %}
                    <div class="col-md-4 sm-mb-30">
                        <div class="counter-item text-center">
                            <div class="counter-bg">
                                <img src="/static/assets/images/counter/bg1.png" alt="Counter Image">
                            </div>
                            <div class="counter-text">

                                <h2 class="">{{ obj.value }}</h2>
                                <h4 class="title mb-0">{{ obj.name }}</h4>
                            </div>
                        </div>
                    </div>
                {% endfor %}


            </div>
        </div>
    </div>
    <!-- Counter Section End -->

    <!-- Faq Section Start -->
    <div class="rs-faq-part style1 orange-color pt-100 pb-100 md-pt-70 md-pb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 padding-0">
                    <div class=" main-part">
                        <div class="title mb-40 md-mb-15">
                            <h2 class="text-part">{% trans 'Tez-tez verilən suallar' %}</h2>
                        </div>
                        <div class="faq-content">
                            <div class="accordion" id="accordionExample">

                                {% for obj in faq %}
                                    <div class="accordion-item card">
                                        <div class="accordion-header card-header" id="{{ obj.id_heading }}">
                                            <button class="card-link accordion-button collapsed" type="button"
                                                    data-bs-toggle="collapse" data-bs-target="#{{ obj.id_collapse }}"
                                                    aria-expanded="false" aria-controls="{{ obj.id_collapse }}">
                                                {{ obj.name }}
                                            </button>
                                        </div>
                                        <div id="{{ obj.id_collapse }}" class="accordion-collapse collapse"
                                             aria-labelledby="{{ obj.id_heading }}" data-bs-parent="#accordionExample">
                                            <div class="accordion-body card-body">{{ obj.feedback_content|safe }}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 padding-0">
                    {% for obj in breadcrumbs %}
                    <div style="background: url({{obj.f_image_r.url}});" class="img-part media-icon orange-color">
                        <i class="fa fa-play"></i>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- faq Section Start -->


    <!-- Testimonial Section Start -->
    <div style="{% for obj in breadcrumbs %}background: url({{obj.comment_image.url}});{% endfor %}" class="rs-testimonial main-home pt-50 pb-50 mb-100 md-pt-70 md-pb-70">
        <div class="container">
            <div class="sec-title3 mb-50 md-mb-30 text-center">
                <h2 class="title white-color">{% trans 'ŞƏRHLƏR' %}</h2>
            </div>
            <div class="rs-carousel owl-carousel"
                 data-loop="true"
                 data-items="2"
                 data-margin="30"
                 data-autoplay="true"
                 data-hoverpause="true"
                 data-autoplay-timeout="5000"
                 data-smart-speed="800"
                 data-dots="true"
                 data-nav="false"
                 data-nav-speed="false"

                 data-md-device="2"
                 data-md-device-nav="false"
                 data-md-device-dots="true"
                 data-center-mode="false"

                 data-ipad-device2="1"
                 data-ipad-device-nav2="false"
                 data-ipad-device-dots2="true"

                 data-ipad-device="2"
                 data-ipad-device-nav="false"
                 data-ipad-device-dots="true"

                 data-mobile-device="1"
                 data-mobile-device-nav="false"
                 data-mobile-device-dots="false">
                {% for obj in feedback %}
                    <div class="testi-item">
                        <div class="author-desc">
                            <div class="desc"><img class="quote"
                                                   src="/static/assets/images/testimonial/main-home/test-2.png" alt="">
                                {{ obj.feedback_content|safe }}
                            </div>
                            <div class="author-img">
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Testimonial Section End -->

    <!-- Blog Section Start -->

{% endblock %}